var root = {
    name:'D盘',
	size:240000,
    children:[
        {
            name:'电影',
			size:60000,
            children:[
                {
                    name:'美国电影',size:40000
                },
                {
                    name:'日本电影',size:20000
                }
            ]                  
        },
		{
			name:'音乐',size:60000
		},
		{
            name:'学习',
			size:40000,
            children:[
				{
					name:'课件',size:30000
				},
                {
                    name:'电子书',
					size:10000,
                    children:[
                                {name:'茶馆',size:6000},
                                {name:'红与黑',size:4000}
                    ]
                }
            ]
        },
		{
			name:'论文',size:30000
		},
		{
			name:'照片',size:20000
		},
		{
			name:'游戏',size:20000
		},
		{
			name:'女朋友',size:10000
		},
    ]
}